/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

/**
 *
 * @author enzob
 */
public class TelaLivros extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivros
     */
    public TelaLivros() {
    initComponents();
    carregarTabela();
}
private void carregarTabela() {
    String[] colunas = {"ID", "Título", "Autor", "Categoria", "Status"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colunas, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    for (Livro l : Dados.get().getLivros()) {
        model.addRow(new Object[]{
            l.getId(), l.getTitulo(), l.getAutor(),
            l.getCategoria(), l.isDisponivel() ? "Disponível" : "Emprestado"
        });
    }
    tblLivros.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        spLivros = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gerenciar Livros");

        txtBusca.setText(" ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spLivros.setViewportView(tblLivros);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(105, 105, 105)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(btnExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusca))
                            .addComponent(spLivros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spLivros, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
 String titulo = javax.swing.JOptionPane.showInputDialog(this, "Título:");
if (titulo == null || titulo.trim().isEmpty()) return;
String autor = javax.swing.JOptionPane.showInputDialog(this, "Autor:");
if (autor == null || autor.trim().isEmpty()) return;
String categoria = javax.swing.JOptionPane.showInputDialog(this, "Categoria:");
Dados.get().adicionarLivro(new Livro(
    0,
    titulo.trim(), autor.trim(),
    categoria != null ? categoria.trim() : ""
));
carregarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Livro cadastrado!");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
int row = tblLivros.getSelectedRow();
if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um livro."); return; }
int id = (int) tblLivros.getValueAt(row, 0);
Livro l = Dados.get().getLivros().stream().filter(x -> x.getId() == id).findFirst().orElse(null);
if (l == null) return;
String titulo = javax.swing.JOptionPane.showInputDialog(this, "Título:", l.getTitulo());
if (titulo == null || titulo.trim().isEmpty()) return;
String autor = javax.swing.JOptionPane.showInputDialog(this, "Autor:", l.getAutor());
String categoria = javax.swing.JOptionPane.showInputDialog(this, "Categoria:", l.getCategoria());
l.setTitulo(titulo.trim());
l.setAutor(autor != null ? autor.trim() : "");
l.setCategoria(categoria != null ? categoria.trim() : "");
Dados.get().atualizarLivro(l);
carregarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Livro atualizado!");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
int row = tblLivros.getSelectedRow();
    if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um livro."); return; }
    int id = (int) tblLivros.getValueAt(row, 0);
    Livro l = Dados.get().getLivros().stream().filter(x -> x.getId() == id).findFirst().orElse(null);
    if (l == null) return;
    int conf = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir \"" + l.getTitulo() + "\"?");
    if (conf == javax.swing.JOptionPane.YES_OPTION) {
        Dados.get().removerLivro(l);
        carregarTabela();
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String termo = txtBusca.getText().trim().toLowerCase();
String[] colunas = {"ID", "Título", "Autor", "Categoria", "Status"};
javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colunas, 0) {
    public boolean isCellEditable(int r, int c) { return false; }
};
for (Livro l : Dados.get().getLivros()) {
    if (l.getTitulo().toLowerCase().contains(termo) || l.getAutor().toLowerCase().contains(termo)) {
        model.addRow(new Object[]{
            l.getId(), l.getTitulo(), l.getAutor(),
            l.getCategoria(), l.isDisponivel() ? "Disponível" : "Emprestado"
        });
    }
}
tblLivros.setModel(model);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane spLivros;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
