/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

/**
 *
 * @author enzob
 */
public class TelaEmprestimos extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimos
     */
    public TelaEmprestimos() {
    initComponents();
    carregarTabela();
}
private void carregarTabela() {
    String[] colunas = {"ID", "Livro", "Usu\u00e1rio", "Data", "Status"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colunas, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    for (Emprestimo e : Dados.get().getEmprestimos()) {
        model.addRow(new Object[]{
            e.getId(), e.getLivro().getTitulo(),
            e.getUsuario().getNome(),
            e.getDataEmprestimo(), e.getStatus()
        });
    }
    tblEmprestimos.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Empr\u00e9stimos");

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmprestimos);

        btnNovo.setText("Novo Empr\u00e9stimo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnDevolver.setText("Registrar Devolu\u00e7\u00e3o");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnDevolver)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnDevolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
java.util.List<Livro> disponiveis = new java.util.ArrayList<>();
for (Livro l : Dados.get().getLivros()) {
    if (l.isDisponivel()) disponiveis.add(l);
}
if (disponiveis.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Nenhum livro dispon\u00edvel.");
    return;
}
Livro[] livrosArr = disponiveis.toArray(new Livro[0]);
Livro livroEscolhido = (Livro) javax.swing.JOptionPane.showInputDialog(
    this, "Escolha o livro:", "Novo Empr\u00e9stimo",
    javax.swing.JOptionPane.QUESTION_MESSAGE, null, livrosArr, livrosArr[0]);
if (livroEscolhido == null) return;

java.util.List<Usuario> usuarios = Dados.get().getUsuarios();
if (usuarios.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Nenhum usu\u00e1rio cadastrado.");
    return;
}
Usuario[] usuariosArr = usuarios.toArray(new Usuario[0]);
Usuario usuarioEscolhido = (Usuario) javax.swing.JOptionPane.showInputDialog(
    this, "Escolha o usu\u00e1rio:", "Novo Empr\u00e9stimo",
    javax.swing.JOptionPane.QUESTION_MESSAGE, null, usuariosArr, usuariosArr[0]);
if (usuarioEscolhido == null) return;

Emprestimo emp = new Emprestimo(0, usuarioEscolhido, livroEscolhido);
livroEscolhido.setDisponivel(false);
Dados.get().adicionarEmprestimo(emp);
carregarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Empr\u00e9stimo registrado!");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
    int row = tblEmprestimos.getSelectedRow();
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um empr\u00e9stimo.");
        return;
    }
    int id = (int) tblEmprestimos.getValueAt(row, 0);
    Emprestimo emp = Dados.get().getEmprestimos().stream().filter(e -> e.getId() == id).findFirst().orElse(null);
    if (emp == null) return;
    if ("DEVOLVIDO".equals(emp.getStatus())) {
        javax.swing.JOptionPane.showMessageDialog(this, "Este livro j\u00e1 foi devolvido.");
        return;
    }
    int conf = javax.swing.JOptionPane.showConfirmDialog(this, "Confirmar devolu\u00e7\u00e3o de \"" + emp.getLivro().getTitulo() + "\"?");
    if (conf == javax.swing.JOptionPane.YES_OPTION) {
        emp.setStatus("DEVOLVIDO");
        emp.getLivro().setDisponivel(true);
        Dados.get().devolverEmprestimo(emp);
        carregarTabela();
        javax.swing.JOptionPane.showMessageDialog(this, "Devolu\u00e7\u00e3o registrada!");
    }
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimos;
    // End of variables declaration//GEN-END:variables
}