/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;
 
/**
 *
 * @author enzob
 */
public class TelaUsuarios extends javax.swing.JFrame {
 
    /**
     * Creates new form TelaUsuarios
     */
    public TelaUsuarios() {
    initComponents();
    carregarTabela();
}
private void carregarTabela() {
    String[] colunas = {"ID", "Nome", "CPF", "Email"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colunas, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    for (Usuario u : Dados.get().getUsuarios()) {
        model.addRow(new Object[]{u.getId(), u.getNome(), u.getCpf(), u.getEmail()});
    }
    tblUsuarios.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
 
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
        jLabel1.setText("Gerenciar Usu\u00e1rios");
 
        txtBusca.setText(" ");
 
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
 
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);
 
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
 
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
 
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnExcluir))
                    .addComponent(txtBusca))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
 
        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
String nome = javax.swing.JOptionPane.showInputDialog(this, "Nome:");
if (nome == null || nome.trim().isEmpty()) return;
String cpf = javax.swing.JOptionPane.showInputDialog(this, "CPF:");
if (cpf == null || cpf.trim().isEmpty()) return;
String email = javax.swing.JOptionPane.showInputDialog(this, "Email:");
Dados.get().adicionarUsuario(new Usuario(
    0,
    nome.trim(), cpf.trim(),
    email != null ? email.trim() : ""
));
carregarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Usu\u00e1rio cadastrado!");
    }//GEN-LAST:event_btnNovoActionPerformed
 
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int row = tblUsuarios.getSelectedRow();
    if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um usu\u00e1rio."); return; }
    int id = (int) tblUsuarios.getValueAt(row, 0);
    Usuario u = Dados.get().getUsuarios().stream().filter(x -> x.getId() == id).findFirst().orElse(null);
    if (u == null) return;
    String nome = javax.swing.JOptionPane.showInputDialog(this, "Nome:", u.getNome());
    if (nome == null || nome.trim().isEmpty()) return;
    String cpf = javax.swing.JOptionPane.showInputDialog(this, "CPF:", u.getCpf());
    String email = javax.swing.JOptionPane.showInputDialog(this, "Email:", u.getEmail());
    u.setNome(nome.trim());
    u.setCpf(cpf != null ? cpf.trim() : "");
    u.setEmail(email != null ? email.trim() : "");
    Dados.get().atualizarUsuario(u);
    carregarTabela();
    javax.swing.JOptionPane.showMessageDialog(this, "Usu\u00e1rio atualizado!");
    }//GEN-LAST:event_btnEditarActionPerformed
 
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    int row = tblUsuarios.getSelectedRow();
    if (row < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Selecione um usu\u00e1rio."); return; }
    int id = (int) tblUsuarios.getValueAt(row, 0);
    Usuario u = Dados.get().getUsuarios().stream().filter(x -> x.getId() == id).findFirst().orElse(null);
    if (u == null) return;
    int conf = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir \"" + u.getNome() + "\"?");
    if (conf == javax.swing.JOptionPane.YES_OPTION) {
        Dados.get().removerUsuario(u);
        carregarTabela();
    }
    }//GEN-LAST:event_btnExcluirActionPerformed
 
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String termo = txtBusca.getText().trim().toLowerCase();
String[] colunas = {"ID", "Nome", "CPF", "Email"};
javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colunas, 0) {
    public boolean isCellEditable(int r, int c) { return false; }
};
for (Usuario u : Dados.get().getUsuarios()) {
    if (u.getNome().toLowerCase().contains(termo) || u.getCpf().toLowerCase().contains(termo)) {
        model.addRow(new Object[]{u.getId(), u.getNome(), u.getCpf(), u.getEmail()});
    }
}
tblUsuarios.setModel(model);
    }//GEN-LAST:event_btnBuscarActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}